### ISSUE TITLE
rules  seperate_yBAM seperate_mtBAM

### ISSUE THREAD

**Issue by andreott** [morm24/yseq-pipeline#3]
Are mostly duplicates. Could be easily formulated as a single rule. In this way even by just using the chromosome as wildcard (as it is in the result filenames anyway).

So instead of 
```python
YBAM = results_prefix / "{YSEQID}_bwa-mem_{REF}_chrY.bam"
```
and
```python
MTBAM = results_prefix / "{YSEQID}_bwa-mem_{REF}_rCRS_chrM.bam"
```

just
```python
CHRBAM = results_prefix / "{YSEQID}_bwa-mem_{REF}_{chr}.bam"
```

If the `_rCRS` part for chrM outfile is essential, this would also work, so the wildcard would then take the value "rCRS_chrM". The you would just need to convert this into "chrM" within params and use this as target name in the samtools call.

Also I doubt this part can make use of many cores

**Comment by morm24** [comment]
combined into one rule with wildcards, added into map_fastq.smk
